#!/bin/sh
#
# Patch Weasel Driver for radmind
#
# PatchWeasel 1.0.0
# mikeg@bsd-box.net

## Load driver options from PatchWeasel
PW_DRIVER_host=${PW_DRIVER_host:-""}
PW_DRIVER_checksum=${PW_DRIVER_checksum:-""}

if [ "${PW_DRIVER_host}" != "" ]; then
	PW_DRIVER_host="-h ${PW_DRIVER_host}"
fi
if [ "${PW_DRIVER_checksum}" != "" ]; then
	PW_DRIVER_checksum="-c ${PW_DRIVER_checksum}"
fi

pw_driver_precmd() {
	rc=0
	pw_echo "PatchWeasel radmind driver Updating Pre-Commands."
	ktcheck ${PW_DRIVER_checksum} ${PW_DRIVER_host}
	rc=$?
	if [ $rc -gt 1 ]; then
		pw_error "PatchWeasel radmind precmd failed in ktcheck (${rc})!"
		return $rc
	fi

	if [ $rc -eq 1 ]; then
		pw_echo "Patchweasel radmind - found transcript updates."
	fi

	pw_echo "Patchweasel radmind updating ${PW_SCRIPTDIR} contents"
	pw_echo "fsdiff -A ${PW_DRIVER_checksum} ${PW_SCRIPTDIR} | lapply ${PW_DRIVER_host}"
	fsdiff -A ${PW_DRIVER_checksum} ${PW_SCRIPTDIR} | lapply ${PW_DRIVER_host}
	rc=$?
	if [ $rc -ne 0 ]; then
		pw_error "PatchWeasel radmind precmd failed in fsdiff/lapply (${rc})!"
		return $rc
	fi

	return 0
}

pw_driver_patch() {
	pw_echo "Patchweasel radmind applying differences."
	fsdiff -A ${PW_DRIVER_checksum} / | lapply
}

pw_driver_postcmd() {
	return 0
}

pw_driver_usage() {
	cat <<EOU
	PatchWeasel radmind driver options:
		--server <server>	Specify radmind server to use
		--checksum <checksum>	Specify checksum algorithm to use

EOU
}
